apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: task1
spec:
  selector:
    app: nginx                # Matches the label of the pods created by the deployment
  ports:
    - protocol: TCP           # Protocol for the service
      port: 80                # Port exposed by the service
      targetPort: 80          # Port exposed by the container in the pod
      nodePort: 30280         # The fixed port on the node to access the service
  type: NodePort              # Exposes the service on a static port on all cluster nodes
